ros2_control_node:
  ros__parameters:
    hardware:
      plugin: gazebo_ros2_control/GazeboSystem
      joints:
        - left_wheel_joint
        - right_wheel_joint

    controllers:
      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController
        left_wheel: 'left_wheel_joint'
        right_wheel: 'right_wheel_joint'
        cmd_vel_timeout: 0.5
        publish_rate: 50
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
