ekf_filter_node:
  frequency: 50
  sensor_timeout: 0.1
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false
  publish_tf: true
  publish_acceleration: false

  map_frame: map              # Defaults to "map" if unspecified
  odom_frame: odom            # Defaults to "odom" if unspecified
  base_link_frame: base_link  # Defaults to "base_link" if unspecified
  world_frame: odom           # Defaults to the value of odom_frame if unspecified

  odom0: /odom                # Input topic for odometry data
  odom0_config: [true, true, false,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom0_queue_size: 2
  odom0_nodelay: false
  odom0_differential: false
  odom0_relative: false

  imu0: /imu/data             # Input topic for IMU data
  imu0_config: [false, false, false,
                false, false, true,
                false, false, false,
                false, false, false,
                false, false, false]
  imu0_queue_size: 5
  imu0_nodelay: false
  imu0_remove_gravitational_acceleration: true
